services:
  backend:
    build: .
    restart: "on-failure"
    env_file: .env
    volumes:
      - static-content:/app/backend/staticfiles
      - media:/app/backend/media

  nginx:
    build: ./nginx
    restart: "always"
    volumes:
      - static-content:/www/static
      - media:/www/media
    depends_on:
      - backend
    ports:
      - 80:80
volumes:
  static-content:
  media:
