# Generated by Django 4.1.7 on 2023-02-27 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_item_upload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemtag",
            old_name="name",
            new_name="value",
        ),
    ]
