# Generated by Django 4.1.7 on 2023-02-28 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_pendingtrade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendingtrade",
            old_name="initator",
            new_name="initiator",
        ),
    ]
