# Generated by Django 4.1.7 on 2023-02-26 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_clothingitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
