# Generated by Django 4.1.7 on 2023-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_initator_pendingtrade_initiator"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingitem",
            name="in_pending_trade",
            field=models.BooleanField(default=False),
        ),
    ]
