# Generated by Django 4.1.7 on 2023-02-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_tag_tagmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothingitem",
            name="tags",
        ),
        migrations.AddField(
            model_name="tagmodel",
            name="taggedItems",
            field=models.ManyToManyField(to="api.clothingitem"),
        ),
    ]
