# Generated by Django 4.1.7 on 2023-03-02 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auto_20230228_1930"),
        ("api", "0003_rename_initator_pendingtrade_initiator"),
    ]

    operations = []
