# Generated by Django 4.1.7 on 2023-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_clothingitem_created_at_clothingitem_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingitem",
            name="image",
            field=models.ImageField(upload_to="posts/"),
        ),
    ]
