# Generated by Django 4.1.7 on 2023-03-02 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_clothingitem_in_pending_trade"),
        ("api", "0004_merge_20230302_0939"),
    ]

    operations = []
