# Generated by Django 4.1.7 on 2023-02-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_clothingitem_tags_tagmodel_taggeditems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tagmodel",
            name="taggedItems",
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="tags",
            field=models.ManyToManyField(to="api.tagmodel"),
        ),
    ]
