# Generated by Django 4.1.7 on 2023-03-14 16:24

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_merge_20230302_1125"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievemnt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("colour", models.CharField(max_length=100)),
                (
                    "xp_recieved",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("achiever", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
