# Generated by Django 4.1.7 on 2023-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_merge_20230302_1125"),
    ]

    operations = [
        migrations.AddField(
            model_name="exechangeuser",
            name="verification_code",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
