# Generated by Django 4.1.7 on 2023-02-22 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_tagmodel_taggeditems_clothingitem_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TagModel",
            new_name="ItemTag",
        ),
    ]
