# Generated by Django 4.1.7 on 2023-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_exechangeuser_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="exechangeuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
