# Generated by Django 4.1.7 on 2023-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("TRADE", "Trade Alert!"),
                    ("LEVEL", "Level Up!"),
                    ("LOCATION", "Location unlocked!"),
                    ("ACHIEVEMENT", "Achievement unlocked!"),
                ],
                max_length=50,
            ),
        ),
    ]
