# Generated by Django 4.1.7 on 2023-02-23 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_tagmodel_itemtag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClothingOwner",
        ),
    ]
