# Generated by Django 4.1.7 on 2023-03-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_achievemnt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievemnt",
            name="achiever",
        ),
        migrations.AddField(
            model_name="exechangeuser",
            name="achievements",
            field=models.ManyToManyField(blank=True, to="api.achievemnt"),
        ),
    ]
