# Generated by Django 4.1.7 on 2023-03-08 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_location_traderequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="value",
            new_name="name",
        ),
    ]
