# Generated by Django 4.1.7 on 2023-03-16 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_achievemnt_achiever_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Achievemnt",
            new_name="Achievement",
        ),
    ]
