# Generated by Django 4.1.7 on 2023-03-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_exechangeuser_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exechangeuser",
            name="verification_code",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
