# Generated by Django 4.1.7 on 2023-03-08 17:01

from django.db import migrations

def defaultLocations(apps, schema_editor):
    locations = [
        "Lafrowda",
        "Forum",
        "Holland Hall",
        "Sanctuary",
        "Business School",
        "SWIOT",
        "Peter Chalk",
        "Harrison",
        "Amory",
        "Northcott Theatre"
    ]
    Location = apps.get_model("api", "Location")
    for location in locations:
        obj = Location(name=location)
        obj.save()

class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_rename_value_location_name"),
    ]

    operations = [migrations.RunPython(defaultLocations)]

from django.db import migrations