# Generated by Django 4.1.7 on 2023-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_delete_clothingowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemtag",
            name="tag",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
