# Generated by Django 4.1.7 on 2023-03-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_rename_achievemnt_achievement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
