# Generated by Django 4.1.7 on 2023-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_default_locations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traderequest",
            name="from_location",
        ),
        migrations.AddField(
            model_name="traderequest",
            name="from_locations",
            field=models.ManyToManyField(
                related_name="trade_request_from_loc", to="api.location"
            ),
        ),
        migrations.AddField(
            model_name="traderequest",
            name="to_locations",
            field=models.ManyToManyField(
                related_name="trade_request_to_loc", to="api.location"
            ),
        ),
    ]
