# Generated by Django 4.1.7 on 2023-03-09 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_traderequest_from_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traderequest",
            name="from_locations",
        ),
        migrations.RemoveField(
            model_name="traderequest",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="traderequest",
            name="giving",
        ),
        migrations.RemoveField(
            model_name="traderequest",
            name="receiving",
        ),
        migrations.RemoveField(
            model_name="traderequest",
            name="to_locations",
        ),
        migrations.RemoveField(
            model_name="traderequest",
            name="to_user",
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="description",
            field=models.TextField(default=None, max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="traderequest",
            name="giver",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade_request_giver",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="traderequest",
            name="items",
            field=models.ManyToManyField(
                related_name="trade_request_items", to="api.clothingitem"
            ),
        ),
        migrations.AddField(
            model_name="traderequest",
            name="message",
            field=models.TextField(default=None, max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="traderequest",
            name="receiver",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade_request_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="traderequest",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("R", "Rejected")], default="P", max_length=1
            ),
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("U", "Upcoming"),
                            ("R", "Rejected"),
                            ("A", "Accepted"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("time", models.DateTimeField()),
                ("giver_there", models.BooleanField(default=False)),
                ("receiver_there", models.BooleanField(default=False)),
                ("confirmation_code", models.PositiveSmallIntegerField(default=7436)),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_giver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "giver_giving",
                    models.ManyToManyField(
                        related_name="trade_giving", to="api.clothingitem"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.location"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver_exchanging",
                    models.ManyToManyField(
                        related_name="trade_exchanging", to="api.clothingitem"
                    ),
                ),
            ],
        ),
    ]
