# Generated by Django 4.1.7 on 2023-03-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_traderequest_from_locations_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clothingitem",
            old_name="in_pending_trade",
            new_name="in_trade",
        ),
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(default=2213),
        ),
        migrations.DeleteModel(
            name="PendingTrade",
        ),
    ]
