# Generated by Django 4.1.7 on 2023-03-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_rename_in_pending_trade_clothingitem_in_trade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="message",
            field=models.TextField(default=None, max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(default=4955, editable=False),
        ),
        migrations.AlterField(
            model_name="trade",
            name="location",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.location",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="receiver_exchanging",
            field=models.ManyToManyField(
                blank=True, related_name="trade_exchanging", to="api.clothingitem"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("R", "Rejected"),
                    ("U", "Upcoming"),
                    ("A", "Accepted"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="time",
            field=models.DateTimeField(blank=True),
        ),
        migrations.DeleteModel(
            name="TradeRequest",
        ),
    ]
