# Generated by Django 4.1.7 on 2023-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_trade_confirmation_code_alter_trade_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(default=3779, editable=False),
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("R", "Rejected"),
                    ("A", "Accepted"),
                    ("C", "Completed"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
