# Generated by Django 4.1.7 on 2023-03-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_trade_confirmation_code_alter_trade_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(default=6459, editable=False),
        ),
    ]
