# Generated by Django 4.1.7 on 2023-03-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_trade_accepted_at_trade_requested_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(default=2869, editable=False),
        ),
        migrations.AlterField(
            model_name="trade",
            name="message",
            field=models.TextField(blank=True, max_length=280),
        ),
    ]
