# Generated by Django 4.1.7 on 2023-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_trade_confirmation_code_alter_trade_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothingitem",
            name="in_trade",
        ),
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(default=6405, editable=False),
        ),
    ]
