# Generated by Django 4.1.7 on 2023-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_remove_clothingitem_in_trade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(default=2022, editable=False),
        ),
    ]
