# Generated by Django 4.1.7 on 2023-03-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_trade_confirmation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="exechangeuser",
            name="items_given",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exechangeuser",
            name="items_received",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exechangeuser",
            name="items_removed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exechangeuser",
            name="items_uploaded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exechangeuser",
            name="trades_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(default=1109, editable=False),
        ),
    ]
