# Generated by Django 4.1.7 on 2023-03-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_exechangeuser_items_given_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingitem",
            name="hidden",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(default=7954, editable=False),
        ),
    ]
