# Generated by Django 4.1.7 on 2023-03-22 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_exechangeuser_verification_code"),
        ("api", "0023_alter_trade_confirmation_code"),
    ]

    operations = []
