# Generated by Django 4.1.7 on 2023-03-22 17:31

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_merge_20230322_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="confirmation_code",
            field=models.PositiveSmallIntegerField(
                default=apps.api.models.Trade.generate_confirmation_code, editable=False
            ),
        ),
    ]
