# Generated by Django 4.1.7 on 2023-03-22 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_exechangeuser_verification_code"),
        ("api", "0025_alter_trade_confirmation_code"),
    ]

    operations = []
