# Generated by Django 4.1.7 on 2023-03-22 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_notification_notification_type"),
        ("api", "0026_merge_20230322_1735"),
    ]

    operations = []
