# Generated by Django 4.1.7 on 2023-03-22 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_rename_achievemnt_achievement"),
        ("api", "0026_merge_20230322_1735"),
    ]

    operations = []
