name: "Continuous Integration"
on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm-install:
    uses: ./.github/workflows/npm-install.yml

  npm-test:
    needs: npm-install
    uses: ./.github/workflows/npm-test.yml

  npm-lint:
    needs: npm-install
    uses: ./.github/workflows/npm-lint.yml

  npm-format:
    needs: npm-install
    uses: ./.github/workflows/npm-format.yml
