name: "Frontend Continuous Integration"
on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  npm-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.6.0
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
          cache: "npm"
      - run: npm ci
      - name: Testing
        run: npm run check-test
      - name: Linting
        run: npm run lint
      - name: Checking Code Format
        run: npm run check-format
