name: Backend Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  python-ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Run pytest
        run: |
          PYTHONPATH=$PYTHONPATH:$PWD/backend poetry run pytest
      - name: Run Linting
        run: |
          PYTHONPATH=$PYTHONPATH:$PWD/backend poetry run pylint backend/apps
          PYTHONPATH=$PYTHONPATH:$PWD/backend poetry run pylint backend/backend
      - name: Formatting
        run: |
          poetry run black --check .
      - name: Sorting
        run: |
          poetry run isort --check .
